tools:
    php_analyzer: true
    php_mess_detector: true
    php_pdepend: true
    php_cpd: false
    php_cs_fixer:
        config: { level: psr2 }
    sensiolabs_security_checker: true
checks:
    php:
        code_rating: true
        duplication: true
